# Define global variables
variables:
- template: Variables/groups.yml

# Define repository
resources:
  repositories:
    - repository: tfpipeline-shared
      type: github
      name: wesley-trust/tfpipeline-shared
      endpoint: 'wesley-trust'

# Define stages
stages:

# Apply
- template: Stages/apply.yml